version: '3'

services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgres/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgres/data
    ports:
      - "6543:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 1s
      timeout: 5s

  migrator:
    build: ./Database/tern
    command:
      - migrate
      - --conn-string
      - postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      - --migrations
      - /migrations
    depends_on:
      db:
        condition: service_healthy

  server:
    build: Database
    restart: always
    ports:
      - "10000:10000"
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      PORT: 10000
    depends_on:
      - migrator

  bot:
    build: ./Bot
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
    depends_on:
      - server

volumes:
  db_data:
